all: main

main: zad1.cpp insertionSort.cpp mergeSort.cpp quickSort.cpp generator.cpp dualPivot.cpp mergeInsertionSort.cpp statistics.cpp
	g++ -o main zad1.cpp insertionSort.cpp mergeSort.cpp quickSort.cpp generator.cpp dualPivot.cpp mergeInsertionSort.cpp statistics.cpp


